[credit."/otter/gallery/otter_pride.png"]
handle = "DaxlMonitor"
url = "https://twitter.com/DaxlMonitor"
[credit."/otter/refsheet.png"]
handle = "Cleini Arkent"
url = "https://twitter.com/CleiArkent"
[credit."/otter/refsheet_unclothed.png"]
handle = "Cleini Arkent"
url = "https://twitter.com/CleiArkent"